name: swagger_parser
description: Package that generates REST clients and data classes from OpenApi definition file
version: 1.13.0
repository: https://github.com/Carapacik/swagger_parser/tree/main/swagger_parser
homepage: https://omega-r.com
topics:
  - swagger
  - openapi
  - codegen
  - api
  - json

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.0
  code_builder: ^4.8.0
  collection: ^1.17.1
  dart_style: ^2.3.4
  freezed_annotation: ^2.4.1
  path: ^1.8.3
  recase: ^4.1.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.4.7
  carapacik_lints: ^1.4.2
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  test: ^1.24.4
